project:
  type: website
  output-dir: docs

website:
  title: "E-Wanderer"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: 首页
      - href: posts/page.qmd
        text: 篇文
      - href: about.qmd
        text: 关于
    right:
      - icon: github
        text: 项目仓库
        href: https://github.com

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

