project:
  type: website
  output-dir: docs

website:
  title: "E-Wanderer"
  search: true
  navbar:
    left:
      - text: "首页"
        href: index.qmd
      - text: "关于"
        href: about.qmd
      - text: "其他项目"
        menu: 
          - text: "R学习笔记"
    right:
      - icon: github
        text: "项目仓库"
        href: https://github.com/E-Wanderer/e-wanderer.github.io

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

